# Site settings
title: Dragoș Rotaru blog
email: 
description: "MPC blurbs"
baseurl: ""
url: "http://rdragos.github.io"
twitter_username: DragosRotaru
github_username:  rdragos

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: jekyll-theme-modernist